"""Helpers for installing Agent Eye as a lightweight macOS .app bundle."""

from __future__ import annotations

import plistlib
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import cast

from .__version__ import __version__

APP_BUNDLE_NAME = "Agent Eye.app"
APP_BUNDLE_IDENTIFIER = "com.agenteye.app"
APP_EXECUTABLE_NAME = "Agent Eye"
APP_ICON_NAME = "AgentEye.icns"
APP_GENERATED_KEY = "AgentEyeGeneratedBundle"
APP_GENERATED_VALUE = "python-launcher-v1"

_ICON_SIZES = [(16, 16), (32, 32), (64, 64), (128, 128), (256, 256), (512, 512)]


def default_applications_dir() -> Path:
    """Return the default per-user Applications directory."""
    return Path.home() / "Applications"


def app_bundle_path(applications_dir: Path | None = None) -> Path:
    """Return the Agent Eye bundle path for the given Applications directory."""
    return (applications_dir or default_applications_dir()) / APP_BUNDLE_NAME


def _bundle_contents_path(bundle_path: Path) -> Path:
    return bundle_path / "Contents"


def _bundle_plist_path(bundle_path: Path) -> Path:
    return _bundle_contents_path(bundle_path) / "Info.plist"


def _bundle_macos_path(bundle_path: Path) -> Path:
    return _bundle_contents_path(bundle_path) / "MacOS"


def _bundle_resources_path(bundle_path: Path) -> Path:
    return _bundle_contents_path(bundle_path) / "Resources"


def _bundle_executable_path(bundle_path: Path) -> Path:
    return _bundle_macos_path(bundle_path) / APP_EXECUTABLE_NAME


def _bundle_icon_path(bundle_path: Path) -> Path:
    return _bundle_resources_path(bundle_path) / APP_ICON_NAME


def _icon_source_path() -> Path:
    """Return the shipped PNG asset used to generate the macOS .icns file."""
    static_dir = Path(__file__).resolve().parent / "static"
    for name in ("icon-macos.png", "icon-512.png"):
        candidate = static_dir / name
        if candidate.exists():
            return candidate
    raise RuntimeError("Could not find an Agent Eye icon asset to build the macOS app bundle.")


def _info_plist(python_executable: str) -> dict[str, object]:
    """Build the Info.plist metadata for the generated app bundle."""
    return {
        "CFBundleName": "Agent Eye",
        "CFBundleDisplayName": "Agent Eye",
        "CFBundleIdentifier": APP_BUNDLE_IDENTIFIER,
        "CFBundleExecutable": APP_EXECUTABLE_NAME,
        "CFBundleIconFile": APP_ICON_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": __version__,
        "CFBundleVersion": __version__,
        APP_GENERATED_KEY: APP_GENERATED_VALUE,
        "AgentEyePythonExecutable": python_executable,
    }


def _launcher_script(python_executable: str) -> str:
    """Build the launcher shell script for the generated app bundle."""
    quoted_python = shlex.quote(python_executable)
    return f'#!/bin/sh\nexec {quoted_python} -m src.session_dashboard app --foreground "$@"\n'


def _write_icns(icon_path: Path) -> None:
    """Generate the bundle's .icns file from the shipped macOS PNG icon."""
    from PIL import Image

    source = _icon_source_path()
    with Image.open(source) as image:
        image.save(icon_path, format="ICNS", sizes=_ICON_SIZES)


def is_generated_bundle(bundle_path: Path) -> bool:
    """Return True when the bundle at bundle_path was generated by Agent Eye."""
    if not bundle_path.is_dir():
        return False
    plist_path = _bundle_plist_path(bundle_path)
    if not plist_path.exists():
        return False
    try:
        with plist_path.open("rb") as handle:
            info = cast(dict[str, object], plistlib.load(handle))
    except (OSError, plistlib.InvalidFileException):
        return False
    return (
        info.get(APP_GENERATED_KEY) == APP_GENERATED_VALUE
        and info.get("CFBundleIdentifier") == APP_BUNDLE_IDENTIFIER
        and info.get("CFBundleExecutable") == APP_EXECUTABLE_NAME
    )


def _stage_bundle(bundle_path: Path, python_executable: str) -> None:
    """Create a complete Agent Eye .app bundle at bundle_path."""
    python_path = str(Path(python_executable).resolve())
    _bundle_macos_path(bundle_path).mkdir(parents=True, exist_ok=True)
    _bundle_resources_path(bundle_path).mkdir(parents=True, exist_ok=True)

    with _bundle_plist_path(bundle_path).open("wb") as handle:
        plistlib.dump(_info_plist(python_path), handle)

    executable_path = _bundle_executable_path(bundle_path)
    executable_path.write_text(_launcher_script(python_path), encoding="utf-8")
    executable_path.chmod(0o755)

    _write_icns(_bundle_icon_path(bundle_path))


def _refresh_spotlight(bundle_path: Path) -> None:
    """Ask Spotlight to import the app bundle if mdimport is available."""
    mdimport = shutil.which("mdimport")
    if not mdimport:
        return
    subprocess.run(
        [mdimport, "-f", str(bundle_path)],
        capture_output=True,
        text=True,
        check=False,
    )


def install_app_bundle(
    applications_dir: Path | None = None, python_executable: str | None = None
) -> Path:
    """Install or refresh the generated Agent Eye .app bundle."""
    bundle_path = app_bundle_path(applications_dir)
    applications_path = bundle_path.parent
    applications_path.mkdir(parents=True, exist_ok=True)

    if bundle_path.exists():
        if not is_generated_bundle(bundle_path):
            raise RuntimeError(
                f"Refusing to overwrite existing app at {bundle_path}: "
                "it was not generated by Agent Eye."
            )
        shutil.rmtree(bundle_path)

    staging_root = Path(tempfile.mkdtemp(prefix=".agenteye-app-", dir=applications_path))
    staging_bundle = staging_root / APP_BUNDLE_NAME
    try:
        _stage_bundle(staging_bundle, python_executable or sys.executable)
        staging_bundle.replace(bundle_path)
    finally:
        shutil.rmtree(staging_root, ignore_errors=True)

    _refresh_spotlight(bundle_path)
    return bundle_path


def uninstall_app_bundle(applications_dir: Path | None = None) -> Path | None:
    """Remove the generated Agent Eye .app bundle if present."""
    bundle_path = app_bundle_path(applications_dir)
    if not bundle_path.exists():
        return None
    if not is_generated_bundle(bundle_path):
        raise RuntimeError(
            f"Refusing to remove existing app at {bundle_path}: it was not generated by Agent Eye."
        )
    shutil.rmtree(bundle_path)
    return bundle_path
